version: "2.4"
services:
    prometheus:
        image: prom/prometheus
        links:
            - prometheus-sql:prometheus-sql
        depends_on:
            - prometheus-sql
        ports:
            - 9090:9090
        volumes:
            - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
            - ${PWD}/rules:/etc/prometheus/rules

    sqlagent:
        image: dbhi/sql-agent
        links:
            - mysql:mysql
        depends_on:
            - mysql

    prometheus-sql:
        image: dbhi/prometheus-sql
        links:
            - sqlagent:sqlagent
        depends_on:
            - sqlagent
        ports:
            - 8080:8080
        command:
            - -config
            - /config.yml
            - -service
            - http://sqlagent:5000
        # Specify where the queries file is mounted on the host.
        volumes:
            - ${PWD}/config.yml:/config.yml
            - ${PWD}/queries.yml:/queries.yml

    mysql:
        image: mysql:8
        volumes:
            - ${PWD}/:/docker-entrypoint-initdb.d/:z
        environment:
            MYSQL_ROOT_PASSWORD: unsecure
            MYSQL_USER: test
            MYSQL_PASSWORD: unsecure
            MYSQL_DATABASE: test
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
    
    prom-alertmanager:
        image: prom/alertmanager
        links:
            - prometheus:prometheus
        depends_on:
            - prometheus
        ports:
            - 9093:9093
        volumes:
            - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml